stages:
  - deploy

deploy_production:
  stage: deploy
  tags:
    - proatam-servidor-produccion
  script:
    - echo "Deploy en servidor..."
    - cd /var/www/proatam/public_html
    - git fetch origin
    - git reset --hard origin/main
    - bash deploy.sh