stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - echo "Actualizando servidor..."
    - ssh root@72.62.130.214 "cd /var/www/proatam/public_html && git pull origin main"
  only:
    - main